"""
Milvus service — helper functions consumed by the storage orchestrator.

Responsibilities:
  - Convert raw ChunkPayload list + pre-computed UUIDs into Milvus row dicts.
"""

from core.schema import ChunkPayload
from core.logger import setup_logger
from core.utils.chunk_utils import derive_has_image

logger = setup_logger("milvus_service")


def build_vector_rows(
    document_id: str,
    chunks: list[ChunkPayload],
    chunk_uuids: list[str],
) -> list[dict]:
    """
    Build a list of row dicts ready for Milvus bulk insert.

    Uses the pre-computed UUIDs from postgres_service.build_chunk_rows so that
    chunk_id is **identical** in both PostgreSQL and Milvus.

    Args:
        document_id:  String UUID of the parent document.
        chunks:       List of ChunkPayload from the ingestion service.
        chunk_uuids:  Deterministic UUID strings generated by postgres_service.

    Returns:
        List of dicts with keys: chunk_id, document_id, has_table, has_image, embedding.
    """
    return [
        {
            "chunk_id":    chunk_uuids[i],
            "document_id": document_id,
            "has_table":   chunk.has_table,
            "has_image":   derive_has_image(chunk.image_uri),
            "embedding":   chunk.embedding,
        }
        for i, chunk in enumerate(chunks)
    ]
